apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "glowroot-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "glowroot-chart.name" . }}
    helm.sh/chart: {{ include "glowroot-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "glowroot-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "glowroot-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "CASSANDRA_CONTACT_POINTS"
              value: {{ template "cassandra.fullname" . }}
            - name: "CASSANDRA_USERNAME"
              value: {{ default "" .Values.cassandra.dbUser.user | quote }}
            - name: "CASSANDRA_PASSWORD"
              value: {{ default "" .Values.cassandra.dbUser.password | quote }}
          ports:
            - name: ui-http
              containerPort: 4000
              protocol: TCP
            - name: agent-http
              containerPort: 8181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui-http
          readinessProbe:
            httpGet:
              path: /
              port: ui-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
