apiVersion: v1
kind: Service
metadata:
  name: {{ include "glowroot-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "glowroot-chart.name" . }}
    helm.sh/chart: {{ include "glowroot-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.uiPort }}
      targetPort: ui-http
      protocol: TCP
      name: ui-http
    - port: {{ .Values.service.agentPort }}
      targetPort: agent-http
      protocol: TCP
      name: agent-http
  selector:
    app.kubernetes.io/name: {{ include "glowroot-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
